server:
  port: 8089

spring:
  application:
    name: retailShop-service

  jpa:
    hibernate:
      ddl-auto: create
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: rios
      password: password
  h2:
    console:
      enabled: true
      path: /h2console/



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/



