server:
  port: 8089
  servlet:
    contextPath: /retailShop/

spring:
  application:
    name: retailShop-service

  jpa:
    hibernate:
      ddl-auto: create
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: rios
      password: password
  h2:
    console:
      enabled: true
      path: /h2console/



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://rios-discovery-service.herokuapp.com/eureka/



